
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action CrossTemplateAction;
	private global::Gtk.Action Submenu1Action;
	private global::Gtk.Action MessageboxAction;
	private global::Gtk.Action SystemAction;
	private global::Gtk.Action GTKAction;
	private global::Gtk.Action TestAction;
	private global::Gtk.RadioAction TestAction1;
	private global::Gtk.RadioAction Test2Action;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Label label1;
	private global::Gtk.HButtonBox hbuttonbox1;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.CrossTemplateAction = new global::Gtk.Action ("CrossTemplateAction", "CrossTemplate", null, null);
		this.CrossTemplateAction.ShortLabel = "Menu1";
		w1.Add (this.CrossTemplateAction, null);
		this.Submenu1Action = new global::Gtk.Action ("Submenu1Action", "Submenu 1", null, null);
		this.Submenu1Action.ShortLabel = "Submenu 1";
		w1.Add (this.Submenu1Action, null);
		this.MessageboxAction = new global::Gtk.Action ("MessageboxAction", "Messagebox", null, null);
		this.MessageboxAction.ShortLabel = "Messagebox";
		w1.Add (this.MessageboxAction, null);
		this.SystemAction = new global::Gtk.Action ("SystemAction", "System", null, null);
		this.SystemAction.ShortLabel = "System";
		w1.Add (this.SystemAction, null);
		this.GTKAction = new global::Gtk.Action ("GTKAction", "GTK", null, null);
		this.GTKAction.ShortLabel = "GTK";
		w1.Add (this.GTKAction, null);
		this.TestAction = new global::Gtk.Action ("TestAction", "Test", null, null);
		this.TestAction.ShortLabel = "Test";
		w1.Add (this.TestAction, null);
		this.TestAction1 = new global::Gtk.RadioAction ("TestAction1", "Test", null, null, 0);
		this.TestAction1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.TestAction1.ShortLabel = "Test";
		w1.Add (this.TestAction1, null);
		this.Test2Action = new global::Gtk.RadioAction ("Test2Action", "Test2", null, null, 0);
		this.Test2Action.Group = this.TestAction1.Group;
		this.Test2Action.ShortLabel = "Test2";
		w1.Add (this.Test2Action, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "MainWindow";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'/></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "label1";
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = "System Messagebox";
		this.hbuttonbox1.Add (this.button1);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button1]));
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = "GTK Messagebox";
		this.hbuttonbox1.Add (this.button2);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 485;
		this.DefaultHeight = 96;
		this.Show ();
	}
}
